hmcts/sptribs-dss-update-case-web

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/DTSSTCI-452
Upgrade axios to 1.6.1

DTSSTCI-452

---

Jenkinsfile_CNP
Jenkinsfile_nightly
config/custom-environment-variables.yaml

https://tools.hmcts.net/jira/browse/DTSSTCI-469
Configure secrets in jenkins cnp files

DTSSTCI-469

---

src/main/steps/cookie-banner/template.njk

https://tools.hmcts.net/jira/browse/DTSSTCI-337
Update cookie heading styles

DTSSTCI-337

---

src/main/modules/oidc/index.ts
src/main/routes/authless/routes.ts
src/main/steps/dss-update/confirmation-page/content.test.ts
src/main/steps/dss-update/confirmation-page/content.ts
src/main/steps/dss-update/confirmation-page/postController.test.ts
src/main/steps/dss-update/confirmation-page/postController.ts
src/main/steps/dss-update/confirmation-page/template.njk
src/main/steps/dss-update/subject-details/postController.ts

https://tools.hmcts.net/jira/browse/DTSSTCI-355
Configure content for confirmation page and clear session once the user clicks out of the page

DTSSTCI-355

---

charts/sptribs-dss-update-case-web/Chart.yaml
charts/sptribs-dss-update-case-web/values.yaml
config/default.yaml
src/main/modules/helmet/index.ts
src/main/modules/nunjucks/index.ts
src/main/modules/properties-volume/index.ts
src/main/routes/authless/landing/landing.njk
src/main/steps/common/page.njk

https://tools.hmcts.net/jira/browse/DTSSTCI-557
Add dynatrace tags to sptribs dss update case

DTSSTCI-557

---

sonar-project.properties
src/main/app/form/validation.test.ts
src/main/app/form/validation.ts
src/main/modules/helmet/index.test.ts
src/main/modules/oidc/index.test.ts
src/main/steps/upload-documents/getController.test.ts
src/main/steps/upload-documents/getController.ts

https://tools.hmcts.net/jira/browse/DTSSTCI-640
Exclude content files from sonar report. Should be captured in e2e tests.

DTSSTCI-640 v2

---

charts/sptribs-dss-update-case-web/Chart.yaml
charts/sptribs-dss-update-case-web/values.yaml

https://tools.hmcts.net/jira/browse/DTSSTCI-396
Configure autoscaling for update case web app

DTSSTCI-396

---

src/main/modules/session/index.ts

https://tools.hmcts.net/jira/browse/DTSSTCI-663
Add error listener to handle any socket timeouts

DTSSTCI-663

---

charts/sptribs-dss-update-case-web/Chart.yaml
charts/sptribs-dss-update-case-web/values.yaml

https://tools.hmcts.net/jira/browse/DTSSTCI-395
Enable spot instances in values yaml by default

DTSSTCI-395

---

Jenkinsfile_nightly

Fixing nightly pipelines by:
1. Setting Cron Trigger correctly
2. Disabling things like cross browser tests which are hosted out of repository.

Fixing nightly pipelines

---

Jenkinsfile_CNP
infrastructure/prod.tfvars

added prod config for terraform
https://tools.hmcts.net/jira/browse/DTSSTCI-853

DTSSTCI-853: Added prod.tfvars - infrastructure change

---

package.json
yarn.lock

Add azure dependencies from hmcts properties volumn packed into resolutions
https://tools.hmcts.net/jira/browse/DTSSTCI-880

DTSSTCI-880

---

src/main/app/controller/GetController.test.ts
src/main/app/controller/GetController.ts

Remove redundant block from GetController causing fortify failure
(tested locally against AAT to ensure application not affected)
https://tools.hmcts.net/jira/browse/DTSSTCI-882

DTSSTCI-882

---

src/main/steps/accessibility-statement/content.ts

Add Welsh translations for Accessibility Statement
https://tools.hmcts.net/jira/browse/DTSSTCI-748

DTSSTCI-748

---

src/main/steps/accessibility-statement/content.ts
src/main/steps/accessibility-statement/template.njk
yarn.lock

Update accessibility statement content
https://tools.hmcts.net/jira/browse/DTSSTCI-747

DTSSTCI-747

---

src/main/modules/helmet/index.ts

Update helmet config to use https on domains
https://tools.hmcts.net/jira/browse/DTSSTCI-929

DTSSTCI-929

---

charts/sptribs-dss-update-case-web/values.preview.template.yaml

Added app insights config
https://tools.hmcts.net/jira/browse/DTSSTCI-1066

DTSSTCI-1066: Enabled app insights logging in preview

---

package.json
yarn.lock

Add resolutions for send package to resolve dependency check error
https://tools.hmcts.net/jira/browse/DTSSTCI-1093

DTSSTCI-1093

---

charts/sptribs-dss-update-case-web/Chart.yaml
package.json
yarn.lock

Enter a description.
https://tools.hmcts.net/jira/browse/DTSSTCI-

Use OCI for charts

---

src/test/java/build.gradle

Enter a description.
https://tools.hmcts.net/jira/browse/DTSSTCI-

Update slf4j and include fortify classifier

---

package.json
yarn.lock

Enter a description.
https://tools.hmcts.net/jira/browse/DTSSTCI-

Update form-data to ^4.0.4
